"""Test the full Cold War passage."""

from text_detector import TextDetector

text = """The Cold War was one of the most significant and complex conflicts of the twentieth century, shaping global politics, economics, and culture for nearly half a century. Unlike traditional wars fought directly on battlefields between opposing armies, the Cold War was primarily a struggle for influence and ideological dominance between two superpowers: the United States and the Soviet Union. Beginning shortly after the end of World War II in 1945 and lasting until the collapse of the Soviet Union in 1991, the Cold War was characterized by political tension, military rivalry, nuclear arms competition, and proxy wars fought in distant regions. Though the United States and the Soviet Union never engaged in a full-scale direct war against each other, the constant threat of nuclear annihilation and global confrontation made the Cold War one of the most dangerous periods in modern history.
     The origins of the Cold War can be traced to the aftermath of World War II. The United States and the Soviet Union had been allies against Nazi Germany, but their alliance was based more on necessity than trust. The United States supported capitalism, democracy, and free markets, while the Soviet Union promoted communism and a centrally planned economy under one-party rule. As Germany and much of Europe lay in ruins, both superpowers sought to shape the postwar world according to their own political and economic systems. Disagreements over the future of Eastern Europe, especially Poland and Germany, deepened suspicions. The Soviet Union established communist governments in Eastern European countries, creating a buffer zone against future invasions, while the United States viewed these actions as aggressive expansion. This ideological divide hardened into a global rivalry.
     One of the first major policies that defined the Cold War was the American strategy of containment. The United States sought to prevent the spread of communism beyond the areas where it already existed. This strategy was reflected in the Truman Doctrine, which promised American support to countries resisting communist influence, and the Marshall Plan, which provided economic aid to help rebuild Western Europe. The United States believed that economic stability would prevent the appeal of communism. In response, the Soviet Union tightened its control over Eastern Europe and formed its own economic and military alliances. Europe became divided into two blocs: the Western bloc aligned with the United States and the Eastern bloc under Soviet influence. The symbolic and physical division of Germany, particularly the construction of the Berlin Wall in 1961, came to represent the broader separation between East and West.
     Military alliances further intensified the rivalry. In 1949, the United States and several Western European nations formed the North Atlantic Treaty Organization (NATO), pledging mutual defense against aggression. In response, the Soviet Union established the Warsaw Pact in 1955 with its Eastern European allies. These alliances solidified the division of Europe and ensured that any local conflict risked escalating into a broader confrontation. However, the most alarming aspect of the Cold War was the nuclear arms race. Both superpowers rapidly developed and stockpiled nuclear weapons, including hydrogen bombs far more powerful than those used in World War II. The doctrine of mutually assured destruction (MAD) emerged, meaning that any nuclear attack by one side would result in total destruction for both. While this balance of terror may have prevented direct war, it also kept the world in a constant state of anxiety.
     Although the Cold War remained "cold" in terms of direct conflict between the superpowers, it was fought through proxy wars in other parts of the world. In Korea, Vietnam, Afghanistan, and parts of Africa and Latin America, local conflicts became battlegrounds for the broader ideological struggle. The Korean War (1950–1953) was one of the earliest examples, with the United States supporting South Korea and the Soviet Union and China backing North Korea. The war ended in a stalemate, leaving the Korean Peninsula divided. The Vietnam War similarly reflected Cold War tensions, as the United States attempted to prevent the spread of communism in Southeast Asia. These conflicts were devastating for the countries involved, causing millions of deaths and long-lasting political instability, even though they did not escalate into direct superpower warfare.
     The Cuban Missile Crisis of 1962 marked the closest the world came to nuclear war during the Cold War. When the Soviet Union placed nuclear missiles in Cuba, just ninety miles from the coast of Florida, the United States viewed it as an unacceptable threat. President John F. Kennedy responded with a naval blockade and demanded the removal of the missiles. For thirteen tense days, the world watched as the two superpowers stood on the brink of nuclear confrontation. Ultimately, a compromise was reached: the Soviet Union removed its missiles from Cuba, and the United States secretly agreed to remove missiles from Turkey. The crisis demonstrated the dangers of nuclear brinkmanship and led both sides to establish better communication channels, including a direct hotline between Washington and Moscow.
     Beyond military and political tensions, the Cold War also extended into science, technology, and culture. The Space Race became a powerful symbol of competition between the two superpowers. When the Soviet Union launched Sputnik, the first artificial satellite, in 1957, it shocked the United States and triggered a renewed emphasis on science education and technological development. The rivalry continued as both nations competed to achieve milestones in space exploration. In 1969, the United States landed astronauts on the moon, a significant achievement that demonstrated American technological superiority. Meanwhile, the Cold War influenced domestic politics and culture, particularly in the United States, where fear of communist infiltration led to the Red Scare and the rise of McCarthyism. Accusations of disloyalty damaged careers and created a climate of suspicion.
     During the 1970s, a period known as détente brought a temporary easing of tensions. Both superpowers recognized the dangers and costs of constant confrontation. Arms control agreements such as the Strategic Arms Limitation Talks (SALT) aimed to slow the nuclear arms race. Increased diplomatic engagement and economic exchanges suggested the possibility of a more stable relationship. However, détente was fragile and eventually collapsed, particularly after the Soviet invasion of Afghanistan in 1979. The 1980s saw renewed tensions as the United States increased military spending under President Ronald Reagan, who referred to the Soviet Union as an "evil empire." Yet even during this period of renewed rivalry, efforts toward negotiation continued behind the scenes.
     The final phase of the Cold War was shaped by internal changes within the Soviet Union. Economic stagnation, political repression, and the heavy burden of military spending weakened the Soviet system. When Mikhail Gorbachev came to power in 1985, he introduced reforms known as glasnost (openness) and perestroika (restructuring) in an attempt to modernize the Soviet Union. These reforms unintentionally accelerated the collapse of communist control in Eastern Europe. In 1989, a wave of revolutions swept across the region, and the Berlin Wall fell, symbolizing the end of the division of Europe. By 1991, the Soviet Union itself dissolved into independent republics, effectively ending the Cold War and leaving the United States as the world's sole superpower.
     The Cold War had profound and lasting consequences. It shaped international alliances, influenced domestic policies, and fueled technological innovation. It also caused immense suffering through proxy wars and the constant threat of nuclear destruction. While the end of the Cold War reduced the immediate risk of global nuclear conflict, it did not eliminate geopolitical tensions. Many contemporary international issues, including relations between Russia and the West, have roots in Cold War divisions. Ultimately, the Cold War was not merely a military standoff but a global struggle over ideas, power, and the future direction of humanity. Its legacy continues to influence world affairs, reminding us of both the dangers of ideological conflict and the importance of diplomacy in preventing catastrophic war."""

detector = TextDetector()
result = detector.analyze(text)

# Extract and display results
print("\n" + "="*70)
print("🤠 COLD WAR PASSAGE - TEXT AUTHENTICITY ANALYSIS")
print("="*70)

for item in result['raw']:
    label = item['label']
    score = round(item['score'] * 100, 1)
    print(f"{label}: {score}%")

verdict = result['raw'][0]['label']
confidence = round(result['raw'][0]['score']*100, 1)

print("-"*70)
if verdict == 'REAL':
    print(f"✓ VERDICT: REAL (Human-Written)")
else:
    print(f"✗ VERDICT: FAKE (AI-Generated)")
print(f"Confidence: {confidence}%")
print("="*70 + "\n")
