"""Text detection module.

Analyzes text content for reality detection.
"""

from typing import Any, Dict

from transformers import pipeline


class TextDetector:
    """Detects fake or misleading text content.

    This wrapper uses a pretrained Transformer model to classify whether
    input text was generated by an LLM (``AI``) or written by a human.

    The default model is ``roberta-base-openai-detector`` from the
    Hugging Face Hub, but you can pass another model name to ``__init__``.
    """

    def __init__(self, model_name: str = "roberta-base-openai-detector"):
        """Initialize text detector.

        Parameters
        ----------
        model_name:
            Hugging Face model identifier for a text‑classification model.
        """
        # create a text‑classification pipeline; the pipeline will download
        # weights the first time it runs if they are not already cached.
        self._pipe = pipeline("text-classification", model=model_name)

    def analyze(self, text: str) -> Dict[str, Any]:
        """Analyze text for authenticity.

        Returns a dictionary containing the labels and scores produced by the
        underlying pipeline.  Example output::

            [
              {'label': 'REAL', 'score': 0.9123},
              {'label': 'FAKE', 'score': 0.0877}
            ]
        """
        # the pipeline expects a single string or list of strings
        result = self._pipe(text)
        # normalize output to a simple dict for callers
        return {"raw": result}

