"""Text detection module.

Analyzes text content for reality detection using Google Gemini API.
"""

import os
from typing import Any, Dict

import google.generativeai as genai


class TextDetector:
    """Detects fake or misleading text content using Gemini.

    Uses the Google Gemini API to analyze text and determine if it was
    AI-generated or human-written.
    """

    def __init__(self, api_key: str = None):
        """Initialize text detector.

        Parameters
        ----------
        api_key:
            Google Gemini API key. If not provided, looks for
            GOOGLE_API_KEY environment variable.
        """
        key = api_key or os.getenv("GOOGLE_API_KEY")
        if not key:
            raise ValueError(
                "No API key provided. Set GOOGLE_API_KEY env var "
                "or pass api_key parameter."
            )
        genai.configure(api_key=key)
        self.model = genai.GenerativeModel("gemini-pro")

    def analyze(self, text: str) -> Dict[str, Any]:
        """Analyze text for authenticity using Gemini.

        Returns a dictionary with Gemini's assessment of whether the text
        appears to be AI-generated or human-written.
        """
        prompt = f"""Analyze the following text and determine if it was written by a human or generated by an AI.
        
Text: {text}

Respond with a JSON object containing:
- "is_ai_generated": boolean
- "confidence": float between 0 and 1
- "reasoning": string explaining your assessment

Only return the JSON, no other text."""

        try:
            response = self.model.generate_content(prompt)
            return {"raw": response.text, "model": "gemini-pro"}
        except Exception as e:
            return {"raw": str(e), "model": "gemini-pro", "error": True}

